# Generated by Django 2.2.3 on 2020-01-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='CustomerApp.CustomerModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='CustomerApp.CustomerModel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='CustomerApp.PersonsModel')),
            ],
        ),
    ]
