# Generated by Django 2.2.3 on 2020-01-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='date',
            field=models.DateField(default=datetime.date(2020, 1, 17)),
        ),
    ]
