version: '3'
services:
  mysql:
    image: "mysql:5.7"
    environment:
     MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "3306:3306"
    networks:
     - default
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    links:
     - mysql:db
    ports:
     - "8080:80"
    environment:
     MYSQL_ROOT_PASSWORD: 123456