# Generated by Django 2.2.3 on 2020-01-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RƏSMİ', 'Official'), ('QEYRİ-RƏSMİ', 'Unofficial')], max_length=25)),
                ('currency', models.CharField(choices=[('AZN', 'Azn'), ('EUR', 'Eur'), ('USD', 'Usd')], max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='CompanyApp.CompanyModel')),
            ],
        ),
    ]
