# Generated by Django 2.2.3 on 2020-01-17 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyApp', '0001_initial'),
        ('CustomerApp', '0002_auto_20200117_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, limit_choices_to={'parent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='TransactionApp.AssignmentModel')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Expense', 'expense'), ('Revenue', 'revenue'), ('Debt', 'debt')], max_length=10)),
                ('date', models.DateField(default=datetime.date(2020, 1, 17))),
                ('currency', models.CharField(choices=[('AZN', 'AZN'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=4)),
                ('value', models.FloatField()),
                ('azn_value', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CompanyApp.AccountsModel')),
                ('assignment', models.ForeignKey(limit_choices_to={'parent': False}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='TransactionApp.AssignmentModel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.CompanyModel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CustomerApp.CustomerModel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CustomerApp.PersonsModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerApp.ProjectsModel')),
            ],
        ),
    ]
